site_name: Hermes documentation
nav:
    - Home: index.md
    - Available tags: all_tags.md
    - Mip tag map: mip_map.md
    - Balsamic tag map: balsamic_map.md
    - Fluffy tag map: fluffy_map.md
    - Microsalt tag map: microsalt_map.md
