site_name: Hermes documentation
nav:
    - Home: index.md
    - Available tags: all_tags.md
    - Mip-dna tag map: mip-dna_map.md
    - Mip-rna tag map: mip-rna_map.md
    - Balsamic tag map: balsamic_map.md
    - Fluffy tag map: fluffy_map.md
    - Microsalt tag map: microsalt_map.md
    - Mutant tag map: mutant_map.md
    - Rnafusion tag map: rnafusion_map.md
